title = "Very Good Graphics"
baseURL = "https://blog.verygoodgraphics.com/"
languageCode = "en-us"
theme = ["jane"]

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 7              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = "VGG"      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = "VeryGoodGraphics"            # default: author.name ↓        # 默认为下面配置的author.name ↓

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
pygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
pygmentsUseClasses = true # Use CSS classes to format highlighted code
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[langusges]
[languages.en]
  title = "Very Good Graphics Blog"
  languageName = "English"
  languageCode = "en-us"
[languages.zh-cn]
  title = "Very Good Graphics Blog"
  languageName = "中文"
  languageCode = "zh-cn"

[[menu.main]]             # config your menu              # 配置目录
  name = "Blog"
  weight = 10
  identifier = "blog"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/posts/"
[[menu.main]]
  name = "Categories"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "VGG Site"
  weight = 40
  url = "https://verygoodgraphics.com"


[author]                  # essential                     # 必需
  name = "VGG"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2022"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  mainSections = ["posts"]

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "VeryGoodGraphics"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Graphics","Design","Engine"]
  description = "Very Good Graphics Blog"

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 10

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # show language chooser in menu
  showMenuLanguageChooser = true

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "verygoodgraphics/vgg_blog_comments"    # The repo to store comments
    issueTerm = "pathname"
    theme = "github-light"                           # theme: github-light, github-dark, github-dark-orange, icy-dark, dark-blue, photon-dark

  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  [params.gitInfo]
    gitRepo = "https://github.com/verygoodgraphics/verygoodgraphics.github.io"
    showCommitMessage = true

  [params.social]                                         # 社交链接
    g-github = "https://github.com/verygoodgraphics"
